### ISSUE TITLE
Problemi sa zadacima

### ISSUE THREAD

**Issue by Flynt56** [warriorkitty/academy#1]
Radi se o [pripremi za 2. kolokvij](https://github.com/warriorkitty/academy/blob/master/pl-sql/Priprema%20za%202%20kolokvij.pdf).

#### 3. zadatak
>3.) Napraviti triger koji će na svaku bitnu promjenu autora, pozvati proceduru p_postavi_puno_ime i reinicijalizirati puno ime. Student/ica mora sam/a zaključiti koju vrstu trigera koristiti.

Traži se trigger koji bi na `INSERT` ili `UPDATE` možda čak i `DELETE` mijenjao sadržaj tablice **pomoću procedure koja radi nad istom tablicom nad kojom se poziva trigger**. Još se traži svaka promjena autora pa nije jasno je li jednog autora ili svih autora (ovo je više mana hrvatskog jezika).

Procedura `p_postavi_puno_ime` u sebi sadrži `UPDATE` što će se rekurzivno okidati u slučaju da napravimo trigger sa `ON UPDATE` jer rade nad istom tablicom. Nešto slično [ovome](https://stackoverflow.com/questions/33569550/pl-sql-trigger-recursive-error). Time će se trigger okidati sve dok ne ponestane memorije za upit, ali postoji šansa da će sve odraditi za mali broj redova.

Pozivanje procedure ili funkcije unutar triggera koji rade sa istom tablicom kao i trigger sa podacima iz triggera (`new` ili `old` varijable) uzrokuje "Dirty Read" grešku. Nešto slično [ovome](https://stackoverflow.com/questions/20840060/oracle-pl-sql-calling-a-procedure-from-a-trigger).
>ORA-04091: table SYSTEM.AUTORI is mutating, trigger/function may not see it

-----

#### 3. zadatak
>3.) Napraviti triger koji će na promjenu datuma objave u tablici knjige, reinicijalizirati polje
starije_od_30. Potrebno je koristiti p_postavi_starost iz prethodnog zadatka. Student/ica
mora sam/a zaključiti koju vrstu trigera koristiti.

Skoro slična stvar kao i kod prethodnog zadatka. Izbjegnut je slučaj rekurzivnog pozivanja jer se traži trigger na `UPDATE OF datum_objave`, a `UPDATE` u proceduri se radi nad `starije_od_30`. Još uvijek ima problem sa pozivanjem procedure unutar triggera za "Dirty Read" problem.

-----

Bez problema sam riješio oba zadatka bez korištenja procedura u triggerima. Zamolio bi da su zahtjevi malo jasniji kada ima slučaj kao kod 3. zadatka u grupi A sa autorima - da li ažuriramo sve autore ili samo jednog. Mislim da je "Dirty Read" problem kod svakog zadatka koji koristi trigger za zvanje procedure.

**Comment by warriorkitty** [comment]
Poštovani kolega,

u pravu ste, ali smo na vježbama napravili korekciju. Kako ovo nije službeni komunikacijski kanal, molim da mi se javite na email za detalje i novu verziju dokumenta.

Hvala.
